src/pamix_ui.cpp: always use "%s"-style format for printf()-style functions
`ncuses-6.3` added printf-style function attributes and now makes
it easier to catch cases when user input is used in palce of format
string when built with CFLAGS=-Werror=format-security:

    PAmix/src/pamix_ui.cpp:106:52:
     error: format not a string literal and no format arguments [-Werror=format-security]
      106 |   mvprintw(lineNumber++, 1, applicationName.c_str());
          |                                                    ^

Let's wrap all the missing places with "%s" format.